### ISSUE TITLE
#1.4.3 Architecture Diagram

### ISSUE THREAD

**Issue by yichingt** [Inf2001P8-6/INF2001P8-6-Project#10]
Task ID 1.4.3

**Comment by yichingt** [comment]
Work Done: Completed. Defining the service and other external systems/services used for the web application and laying them out in an architecture diagram.
Work committed to repo?: Yes
How does work affect completion deadline: By being able to define and layout the architecture of the system, the team is able to move forward and indicate other requirements or parts that might need to be included with external factors affecting the structure
Any changes to success or completion criteria?: No
Start Date, End Date: 9 Sep - 10 Sep

**Comment by pointlessneedle** [comment]
Description: Diagram to illustrate how the product interacts with the environment, showing the general structure of the system and its associations, limitations and boundaries between the elements.
Goal: Create a visual representation that maps out the physical components for the web application.
Success/Completion: Create a good architecture diagram that illustrates the web application best
Allocated Time: 5 days
Start and End Date: 9 Sep - 13 Sep
Priority: Medium

**Comment by pointlessneedle** [comment]
Work Done: Completed. Defining the service and other external systems/services used for the web application and laying them out in an architecture diagram.
Work committed to repo?: Yes
How does work affect completion deadline: By being able to define and layout the architecture of the system, the team is able to move forward and indicate other requirements or parts that might need to be included with external factors affecting the structure
Any changes to success or completion criteria?: No
Start Date, End Date: 9 Sep - 10 Sep
