### ISSUE TITLE
#1.2.1 Questions for Client

### ISSUE THREAD

**Issue by yichingt** [Inf2001P8-6/INF2001P8-6-Project#2]
Task ID 1.2.1

**Comment by yichingt** [comment]
Task ID 1.2.1
Coming up questions for requirement gathering for client meeting

**Comment by yichingt** [comment]
Completed on 29 Aug.
The tasks has been completed with a total of five questions to be asked during the client meeting.
If task was unable to be completed in time, the client meeting will have to be pushed back, which in return will push other tasks back as well.
Comment for completion of this task was done on 29 Aug.

**Comment by fatalxs** [comment]
Task ID 1.2.1
Description: Requirement gathering questions to be asked during client meeting
Goals of task: For requirements gathering and confirmation regarding a few aspects of the web management system that you have requested.
Success or completion criteria: Questions to be asked
Allocated Time: 1-2 days
Start Date: 29 Aug
End Date: 29 Aug
Owner of task: Syafeen ( @fatalxs )
Priority: High

**Comment by fatalxs** [comment]
Completed on 29 Aug.
The tasks has been completed with a total of five questions to be asked during the client meeting.
If task was unable to be completed in time, the client meeting will have to be pushed back, which in return will push other tasks back as well.
Comment for completion of this task was done on 29 Aug.
