### ISSUE TITLE
#1.4.1.1 Use Case Descriptions

### ISSUE THREAD

**Issue by Renziah** [Inf2001P8-6/INF2001P8-6-Project#20]

**Comment by fatalxs** [comment]
Task ID 1.4.1.1
Description: Use Case Descriptions for the product, with reference to the Use Case Diagram
Goals of task: Generating a list of use case descriptions and costs with reference to the system/product's use case diagram.
Success or completion criteria: All use case descriptions generated
Allocated Time: 4 days
Start Date: 13 Sept
End Date: 16 Sept
Owner of task: Syafeen ( @fatalxs )
Priority: Medium

**Comment by fatalxs** [comment]
The task has been completed on 16 Sept.
If task was unable to be completed in time, the M1 submission would be delayed since the use case descriptions were not completed.
Comment for completion of this task was done on 23 Sept as this issue was inadvertently overlooked previously.
