### ISSUE TITLE
Observations and Improvements to M1

### ISSUE THREAD

**Issue by yichingt** [Inf2001P8-6/INF2001P8-6-Project#28]

**Comment by yichingt** [comment]
Some observations that can be seen was the hectic schedules of the team members due to other commitments causes some difficulty in keeping up to the progress of the tasks.
M1 can be improved by ensuring a smooth engagement with Client to make requirements gathering uncomplicated and overrun, as well as being able to reach out to the Client easier to clear some of the teams queries so as to ensure the project goes without problems.

**Comment by yunzhxn** [comment]
Good communication within the group
Very difficult to reach out to the Client.

**Comment by pointlessneedle** [comment]
While the group worked together sufficiently to reach the goals set in the beginning, a lack of meaningful communication with the client made things difficult. 
Some internal deadlines were not met on time due to underestimation or overlooking of tasks. However, this did not affect the final deadline.

**Comment by Renziah** [comment]
The team had a good amount of teamwork, willing to carry each other's burdens wherever needed. Additionally, the team was timely on tasks that they were delegated to. 

One thing I wish could be changed about the team is the amount of physical meetings. Most of the meetings that we have can be done online, saving travel time. [ we can have more online meetings with clearer objectives in mind ]

M1 can be further improved with better communications with the client, who unfortunately only answered our questions given to him via email 1 day before the submission date.

**Comment by fatalxs** [comment]
Project was more or less smooth sailing so far. Any changes to requirements and needs were adapted to relatively quickly and resolved within the team. Conflicts were minimal and the biggest issue we had was the time constraint versus the other commitments each team member had, but I would say we managed it well.

Further improvements could be made by having a more targetted agenda for meetings and conducting them online, setting deadlines with respect to the assignee's commitment level and working towards the final goal of the project with a balanced workload for all.
