### ISSUE TITLE
#1.6.1 Prepare Presentation for M1

### ISSUE THREAD

**Issue by yichingt** [Inf2001P8-6/INF2001P8-6-Project#5]
Task ID 1.6.1
Description: Preparing presentation slides and content
Goals: To prepare content for presentation
Success/Completion criteria: Complete a good presentation slides
Allocated Time: 5 days
Start and End Date: 19 Sep to 23 Sep
Priority: Medium

**Comment by pointlessneedle** [comment]
Work Done: Completed
Has the work been committed to repo?: Yes
How does work affect completion?: Work was completed late, however no other tasks were pushed back.
Any changes to success or completion criteria: No.
Start date and end date: 19 Sep to 24 Sep
