### ISSUE TITLE
#1.5.5 Wireframes Prototyping

### ISSUE THREAD

**Issue by yichingt** [Inf2001P8-6/INF2001P8-6-Project#8]
Task ID 1.5.5
Description: Prototype of the web application with wireframing to depict what the web app would look like
Goal: Come up with a prototype that best matches what the requirement wants and what to do
Success/Completion: Successfully coming up with a prototype to demo that is the closest or has all the requirements that the client want to look and have
Allocated Time: 1 and a half week
Start and End Date: 6 Sep - 16 Sep
Priority: High

**Comment by pointlessneedle** [comment]
Work Done: Completed
Has the work been committed to repo?: Yes
How does work affect completion?: Work was completed late, which led to a slight delay in completion of report writing.
Any changes to success or completion criteria: No.
Start date and end date: 6 Sep - 21 Sep
Additional Comment: This task was closed late as it took longer than anticipated to complete.
