### ISSUE TITLE
#3.1 Finalising Prototype

### ISSUE THREAD

**Issue by pointlessneedle** [Inf2001P8-6/INF2001P8-6-Project#83]
Task ID 3.1
Description: Verify and Validate all aspects of our prototype
Goals: Submit the final prototype to the client with all functional and non-functional requirements being met
Success or Completion Criteria: As described above
Allocated Time: 1 days
Start - End Date: 25 Nov
Priority: Medium

**Comment by Renziah** [comment]
Work Done: Completed
Has the work been committed to repo?: Yes
How does work affect completion?: No other tasks were pushed back
Any changes to success or completion criteria: No.
Start date and end date: 25 Nov
