### ISSUE TITLE
#1.4.2 Activity Diagram

### ISSUE THREAD

**Issue by yichingt** [Inf2001P8-6/INF2001P8-6-Project#9]
Task ID 1.4.2
Description: Flowchart that shows the flow from one activity to another in a system or process. An advanced version of flow chart that modeling the flow from one activity to another activity for the train management service.
Goal: Illustrate all of the web application's activities flow and behaviour
Success/Completion: Completion of the activity diagram
Allocated Time: 4 Days
Start and End Date: 13 Sep - 16 Sep
Priority: Medium

**Comment by yunzhxn** [comment]
Work done: Completed
Has the work been committed to repo?: Yes
How does work affect completion?: Work was not completed late, thus no other tasks were pushed back
Any changes to success or completion criteria: No.
Start date and end date: 13 Sep- 16 Sep
